//
//  389. Find the Difference .swift
//  AlgorithmsWithBasicInput
//
//  Created by Арсентий Халимовский on 22.09.2023.
//

import Foundation

/*
 
 389. Find the Difference
 
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
 */

func findTheDifference(_ s: String, _ t: String) -> Character {
    var internalT = t
    
        for char in t {
            for letter in s {
                if letter == char {
                    if internalT.count == 1 {
                        break
                    }
                    internalT.remove(at: internalT.firstIndex(of: letter)!)
                    
                }
            }
        }
    return Array(internalT)[0]
    }
